name: schedule

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main

jobs:
  excute-python:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: excute python
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          AUTHORIZATION=$AUTHORIZATION
          printenv
          python get_qiita_article.py
          git add .
          git commit -m "update by github action"
          git push
